print('Привет, мир')
print('你好世界')
print('olá mundo')
print('salve mundo')
print('hello, world')
print('Hallo welt')
print('Geia sou Kósmo')
print('Kamusta yatu')
print('Ni hao shijie')
print('shlum olam')